name: Deploy

on:
  push:
    branches: [ dev ]

jobs:
  app-deploy:

    runs-on: ubuntu-latest
    steps:
      - name: pull changes from github
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al
